### ISSUE TITLE
[POST /user/search] In /user/search response 500 Internal Server Error - need 400 Bad request

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#292]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in as Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on POST /user/search
3. Click on 'Try out'
4. Enter invalid data 

**Actual result**
Response 500 Internal Server Error

**Expected result**
Response 400 Bad request

**Comment by ushh789** [comment]
I've tried different types of invalid data, for example:

```
{
  "pageable": {
    "page": "not_a_number", // wrong data type
    "size": -1,             // invalid data
    "sort": [1, 2, 3]       // wrong data type
  },
  "userViewDto": {
    "id": null,             // shouldn't be null here
    "name": 123,            // wrong type
    "email": "notvalid@mail.com", 
    "userCredo": {},        // shouldn't be an object
    "role": [],             // shouldn't be array here
    "userStatus": ""        // empty value
  }
}
```
But every time I get the same 400 response status:
<img width="370" alt="image" src="https://github.com/OlhenShu/ProjectStage_Team1_May/assets/123461356/e480ca74-afaa-4c6b-8800-1011f4f84b1a">
I think this bug was fixed and the issue should be closed. Please review and write feedback if you find a way to reproduce the bug.

**Comment by tellmant** [comment]
No changes are required, issue seem to be resolved.
